/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#111111',
        'on-primary': '#ffffff',
        canvas: '#ffffff',
        'soft-cloud': '#f5f5f5',
        ink: '#111111',
        charcoal: '#39393b',
        ash: '#4b4b4d',
        mute: '#707072',
        stone: '#9e9ea0',
        hairline: '#cacacb',
        'hairline-soft': '#e5e5e5',
        sale: '#d30005',
        'sale-deep': '#780700',
        success: '#007d48',
        'success-bright': '#1eaa52',
        info: '#1151ff',
        'info-deep': '#0034e3',
      },
      spacing: {
        'xxs': '2px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '18px',
        'xl': '24px',
        'xxl': '30px',
        'section': '48px',
      },
      borderRadius: {
        'none': '0px',
        'sm': '18px',
        'md': '24px',
        'lg': '30px',
        'full': '9999px',
      },
      fontFamily: {
        'display': ['Helvetica Now Display', 'Helvetica', 'Arial', 'sans-serif'],
        'sans': ['Helvetica Now Text', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-campaign': ['96px', { lineHeight: '0.9', fontWeight: '500' }],
        'heading-xl': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
        'heading-lg': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
        'heading-md': ['16px', { lineHeight: '1.75', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'button-lg': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
        'button-md': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'button-sm': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
        'link-md': ['16px', { lineHeight: '1.75', fontWeight: '500' }],
        'caption-md': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
        'caption-sm': ['12px', { lineHeight: '1.5', fontWeight: '500' }],
        'utility-xs': ['9px', { lineHeight: '1.75', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
